JLLeitschuh/ktlint-gradle

CHANGELOG.md, build.gradle.kts, src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt
This removes the dependency upon the gradle script kotlin API
The API has changed in gradle 4.0 and does not have binary compatibility.
Closes #9
=> Support Gradle 4.0

src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt
Actually ktlintCheck tasks do nothing related to code formatting, but
they verify validity of kotlin files.
=> Move ktlintCheck tasks to more appropriate verification group.

CHANGELOG.md, README.md, build.gradle.kts, src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt
Fix for issue #8: This pull request adds support for Android projects with applied `kotlin-android` plugin. Also adds applying plugin only to root project - it will scan subprojects and add tasks accordingly.
=> Issue #8 - Add support for Android projects

CHANGELOG.md, src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt
During working on issue #13 I found out that plugin always uses default extension version of ktlint, no matter what version is defined in users project.
=> Fix plugin uses always default ktlint version.

CHANGELOG.md, README.md, src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, src/main/kotlin/org/jlleitschuh/gradle/ktlint/Reporter.kt
Now plugin outputs check task results to build/reports/ktlint/ folder.
Also user can select one of supported report types.
Fixes #13 
=> Add output report and report type.

CHANGELOG.md, README.md, src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt
Allow users to configure whether or not the build should fail if there is some ktlint issues, very useful if getting quality reports from CI.
=> add ignoreFailures configuration for CI builds

CHANGELOG.md, src/main/kotlin/org/jlleitschuh/gradle/ktlint/Reporter.kt
Now plugin closes report output stream after task run is finished.
Fixes #25
=> Fix report output is not closed.

CHANGELOG.md, src/main/kotlin/org/jlleitschuh/gradle/ktlint/Reporter.kt
I reported the problem that I cannot delete ktlint output file for `java.io.IOException` at #25 .
I thought the cause was that output stream was not closed.
However after fixed it, I still couldn't delete the file.
It seems that output stream is always opened.
I googled and found answers like [this](https://discuss.gradle.org/t/exec-standardoutput-to-file-in-builddir-but-no-builddir-yet/17913/2) or [this](https://stackoverflow.com/questions/13172215/gradle-output-file-not-up-to-date-if-parsed-from-standardoutput).
According to those, FileOutputStream should open in `doFirst` closure.
=> Fix report output is always opened since task is created.

CHANGELOG.md, src/main/kotlin/org/jlleitschuh/gradle/ktlint/Reporter.kt
This prevents to use plugin with >0.10.x versions of ktlint.
Fixes #28 
=> Fix wrong parsing of ktlint version.

CHANGELOG.md, src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, src/main/kotlin/org/jlleitschuh/gradle/ktlint/Reporter.kt
While the ktlint checkstyle reporter stream Strings in output file, it generates a corrupted XML after the first sourceSet run.
Fix-it by generating one file by sourceSet, with the following naming: `ktlint-${sourceSetName}.${extension.reporter.fileExtension}`
=> define a different output file for each sourceSet

README.md, settings.gradle.kts
=> Make dependency on Android SDK optional for samples.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt
Fixes #63.
Now running `ktlintCheck` tasks doesn't trigger some android tasks execution:
```
$ ./gradlew -m :samples:android-app:ktlintCheck
:samples:android-app:ktlintDebugAndroidTestCheck SKIPPED
:samples:android-app:ktlintDebugCheck SKIPPED
:samples:android-app:ktlintDebugUnitTestCheck SKIPPED
:samples:android-app:ktlintReleaseCheck SKIPPED
:samples:android-app:ktlintReleaseUnitTestCheck SKIPPED
:samples:android-app:ktlintCheck SKIPPED
BUILD SUCCESSFUL in 1s
```
=> Fix running check task triggers execution of some android tasks.

plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/reporter/Reporter.kt
This reverts commit a5157885bd0382c05cde68ea3eb7b483d0d60939.
This commit leads that reported output created under following path:
```
<subproject-dir>/"/home/myuser/work/ktlint-gradle/samples/kotlin-gradle/build/reports/ktlint/ktlint-main.txt"
```
I've opened issue on ktlint side for better supporting spaces in output path: https://github.com/shyiko/ktlint/issues/177
=> Revert "Quote reporter output path"

plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt
This allows enabling caching for the check task. Without adding a path
sensitivity, caching the check task does not make much sense, since it
would require using the same absolute path to the source files for all
workspaces which want to get cache hits.
See https://guides.gradle.org/using-build-cache/#relocatability.
=> Use relative for input file path sensitivity

CHANGELOG.md, README.md, plugin/build.gradle.kts, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt
New significant release 4.0.0 that has breaking changes.
Additionally:
- Removed deprecated `ReporterType` typealias
- Updated default KtLint version to latest
- Updated changelog with introducing custom rulesets option
=> New release 4.0.0

.travis.yml, plugin/build.gradle.kts
Once a release commit has been pushed, you can simply checkout the `master` branch and run.
```
git tag v[whatever version]
```
From there run `git push --tags` and travis CI will publish the release for you.
Note: Gradle still reads the version from the `version` variable, not from git.
It's expected that these two versions are the same when a release is performed.
Also, I haven't been able to test this yet as it requires performing a release.
=> Configure publishing via Travis CI

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheck.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/AbstractPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
This PR fixes issue that `ktlintCheck` task ignores `.editorconfig` file changes.
For now task assumes that `.editorconfig` file will be either in root project folder or in current project folder. If somebody will need more advanced logic - new issue should be created and this problem will be addressed in a separate PR.
Fixes #106.
=> Fix .editorconfig file change doesn't reset check task state.

CHANGELOG.md, README.md, build.gradle.kts, plugin/build.gradle.kts, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintApplyToIdeaTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintBasePlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheck.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintFormatTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintIdeaPlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/reporter/ReporterType.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt, samples/android-app/build.gradle.kts, samples/kotlin-gradle/build.gradle, samples/kotlin-js/build.gradle.kts, samples/kotlin-ks/build.gradle.kts, samples/kotlin-multiplatform-common/build.gradle.kts, samples/kotlin-multiplatform-js/build.gradle.kts, samples/kotlin-multiplatform-jvm/build.gradle.kts, samples/kotlin-native-konan/build.gradle.kts, samples/kotlin-native/build.gradle.kts, samples/kotlin-rulesets-using/build.gradle.kts
This should improve plugin configuration performance and fix deprecation issue in Gradle `4.10`.
Closes #122 and #111
=> Remove usages of afterEvaluate {}

build.gradle.kts, plugin/build.gradle.kts
This approach is deprecated in Gradle.
=> Remove custom wrapper task.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, samples/android-app/build.gradle.kts
Rethink approach how plugin gets android project sources and now it
uses android plugins base extension information, rather then VariantManager.
This also removes check of the same code more then once.
Closes #131
=> Fix plugin fails to configure android projects with flavors.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
Meta tasks (`ktlintCheck` and `ktlintFormat`) in the project are still visible.
My intention is to reduce unnessesary information, as usually ktlint used by running just `ktlintCheck` (or `ktlintFormat`) tasks.
This hidden tasks can still be visible by running `./gradlew tasks --all`.
=> Hide specific source sets tasks.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt
=> Extent SourceTask for check and format tasks.

plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt
To reduce command line length - pass relative to current project paths
to source files.
Before this change:
```
Command: /opt/oracle-jdk-bin-1.8.0.192/bin/java -Dfile.encoding=UTF-8 -Duser.country=DE -Duser.language=en -Duser.variant -cp <big_classpath> com.github.shyiko.ktlint.Main /home/user/data/work/ktlint-gradle/samples/kotlin-ks/src/main/kotlin/org/jlleitschuh/gradle/ktlint/sample/kotlin/main.kt --verbose --reporter=plain --color --reporter=checkstyle,output=/home/user/data/work/ktlint-gradle/samples/kotlin-ks/build/reports/ktlint/ktlintMainCheck.xml --reporter=json,output=/home/user/data/work/ktlint-gradle/samples/kotlin-ks/build/reports/ktlint/ktlintMainCheck.json
```
After this change:
```
Command: /opt/oracle-jdk-bin-1.8.0.192/bin/java -Dfile.encoding=UTF-8 -Duser.country=DE …
```
=> Pass relative paths to source files in project to ktlint.

plugin/buildSrc/src/main/kotlin/PluginDependencies.kt
New release of SemVer has proper pom published on bintray.
Related to #162
=> Update SemVer to 1.1.1 version.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginVersionTest.kt, samples/kotlin-rulesets-using/build.gradle.kts
After reflecting on last discussion in #153, I think that it is better to rename check/format tasks, so they include `SourceSet` in their name (generated reports names are adjusted as well).
This better reflects on what exactly sources task are working.
Related to #170
=> Use SourceSet in task names and reports files names.

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt
This PR adds android variants meta tasks, that trigger tasks for all source sets in given variant.
For example running `ktlintKellerbierDebugCheck` meta task triggers following tasks:
```bash
$ ./gradlew :samples:android-app:ktlintKellerbierDebugCheck -m
:samples:android-app:ktlintDebugSourceSetCheck SKIPPED
:samples:android-app:ktlintKellerbierDebugSourceSetCheck SKIPPED
:samples:android-app:ktlintKellerbierSourceSetCheck SKIPPED
:samples:android-app:ktlintMainSourceSetCheck SKIPPED
:samples:android-app:ktlintKellerbierDebugCheck SKIPPED
```
Also added limited support for android projects in new Kotlin multiplatform plugin:
```bash
$ ./gradlew -m :samples:kotlin-mpp-android:ktlintKellerbierDebugAndroidLibCheck
:samples:kotlin-mpp-android:ktlintAndroidLibDebugSourceSetCheck SKIPPED …
```
=> Add meta tasks for Android variants

plugin/build.gradle.kts
When building the plugin I get an error due to a failed resolution of `aapt2-proto.jar`.
This is an known issue, see https://stackoverflow.com/questions/52944598/could-not-find-aapt2-proto-jar
=> Avoid error due to failing resolution of aapt2-proto

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintFormatTask.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/AbstractPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
Fixes #194: Format task may produce up-to-date state, if sources was restored to pre-format state, so task input considered to be cached from success run.
Current solution is not perfect, but, currently, there are no better ways in Gradle:
- on first run format changes the sources and produce stable output content 
- on second run gradle produces stable input content with the same output
- on third run task is considered "UP-TO-DATE" and cached
=> Fix wrong up-to-date state of format task.

README.md, plugin/build.gradle.kts, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/AbstractPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintIdeaPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginVersionTest.kt
Now tests are using `GradleRunner.withPluginClasspath()` method to inject plugin under test.
Closes #150.
=> Simplify tests setup.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
This prevents task to reset UP-TO-DATE state on any changes to this file.
Fixes #209
=> Fix .editorconfig in project root is not considered as tasks input.

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/GitHookTasksTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
Add two tasks that install Git `pre-commit` hook:
- `addKtlintCheckGitPreCommitHook`
- `addKtlintFormatGitPreCommitHook`
Hook itself collects all staged (going to be commited) `*.kt` or `*.kts` files and run over this files either ktlint check or format tasks, passing list of files using `-PinternalKtlintGitFilter` property.
This PR partially addresses #101. Currently there are no support for composite builds and `buildSrc` sub-projects. This support should be added in followup PRs.
=> Add pre commit Git hook

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintApplyToIdeaTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
ktlint just released version 0.32.0 to fix a problem with Kotlin 1.3.30. But at the same time, they also changed the maven group id and package names. That is why just updating ktlint version to `0.32.0` breaks ktlint plugin.
I've replaces groups and packages to support the new version. These changes here should be backward compatible.
Since this is only required when using version 0.32.0, I haven't changed the sample repo.
Added test that checks that the correct dependency is added.
Fixes #227
=> Add support for pinterest package and group changes

plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt
When using the plugin with Gradle5.0 or later, the following deprecation warning is shown:
=> Avoid deprecation warning when using Gradle >= 5.0

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/Configurations.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintIdeaPlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, samples/kotlin-rulesets-creating/build.gradle.kts, samples/kotlin-rulesets-using/build.gradle.kts
Added `ktlintRuleset` configuration that allows to provide 3rd party ktlint rules via `dependencies {}` block.
Deprecated related field in plugin extension. Should be removed on next major version change.
Closes #71
=> 3rd party ktlint rules configuration

.travis.yml, CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt
This will allow to use in pure sh shells implementations.
Running `checkbashisms .git/hooks/pre-commit` produces no warnings.
Fixes #251
=> Fix bashisms in git hook.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt
Next release would have breaking changes, so it is good time remove deprecated properties.
=> Remove deprecated `ruleset` extension property.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintFormatTask.kt
Ktlint starts using https://picocli.info/#AtFiles command line option, that
allows to pass arguments to command line invocation from file.
Such approach should solve maximum command line arguments limitation.
Don't need to bump minimum support ktlint version here as picoli dependency on ktlint project was introduced more then 2 years ago, before minimum supported version was released.
Sample of such "args" file for `:samples:kotlin-ks` project:
```
│ File: samples/kotlin-ks/build/ktlint/ktlintMainSourceSetCheck.args
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
1   │ --verbose
2   │ --reporter=plain
3   │ --color
4   │ --reporter=checkstyle,output=/home/egorr/data/work/ktlint-gradle/sam …
```
=> Pass arguments to ktlint as file input.

README.md
When #125 was fixed, reports DSL was changed so that these instructions are not necessary anymore.
Note: I haven't verified that this is the case, It looked like so by looking at the changes. Please verify. Thanks.
=> Remove unneeded FAQ instructions

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, samples/android-app/build.gradle.kts
This has support for the `--color-name` argument added in KtLint 0.35.0: https://github.com/pinterest/ktlint/pull/585
Tested by adding the property to the android-app sample, and forcing a failure.
Before:
After:
=> Added output color name property.

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/TestsCommon.kt
Using `getSources()` is not possible, because:
> Source task doesn’t support `InputChanges` out of the box, since `getSource()` always returns a new instance.
So I was advised to take a look into [JavaCompile](https://github.com/gradle/gradle/blob/16d8de50617a97fbabc1f8a92182b3b648402817/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java) task. I used it as inspiration for incremental support implementation.
Closes #231
=> Add support for incremental task api.

CHANGELOG.md, README.md, plugin/build.gradle.kts, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintFormatTask.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/AbstractPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
Disabled incremental task api for format task. As format task declares output same as input and incremental api deletes all outputs on inputs changes, this lead to files deletion on the second run.
Fixes #302
=> Disable incremental tasks api for format task.

CHANGELOG.md, plugin/build.gradle.kts, plugin/buildSrc/src/main/kotlin/PluginDependencies.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/AbstractPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/BuildCacheTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/DisabledRulesTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/EditorConfigTests.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/GitHookTasksTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KotlinJsPluginTests.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ReportersTest.kt
Now git tasks are always added to avoid I/O on Gradle configuration phase.
Closes #284
=> Plugin will search for .git folder starting from the root project folder to install hook.

plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt
Running a project with the flag `-Dorg.gradle.unsafe.instant-execution=true` results in a failure because:
> task `:ktlintMainSourceSetCheck` of type `org.jlleitschuh.gradle.ktlint.KtlintCheckTask`: invocation of 'Task.project' at execution time is unsupported.
=> Gradle Instant Execution: invocation of 'Task.project' at execution time is unsupported

CHANGELOG.md, README.md, plugin/build.gradle.kts, plugin/buildSrc/src/main/kotlin/PluginDependencies.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, samples/android-app/src/main/java/org/jlleitschuh/gradle/ktlint/android/ItemDetailActivity.kt, samples/android-app/src/main/java/org/jlleitschuh/gradle/ktlint/android/ItemListActivity.kt, samples/kotlin-multiplatform-js/src/main/kotlin/org/jlleitschuh/gradle/ktlint/sample/kotlin/multiplatform/Sample.kt, samples/kotlin-rulesets-creating/src/main/kotlin/org/jlleitschuh/gradle/ktlint/sample/kotlin/NoVarRule.kt
- Use ktlint `0.37.1` by default, which required minor formatting fixes in the android sample app
- Patch updated the Android Gradle plugin from `3.6.0` to `3.6.3` (including the bundled kotlin dependency)
- A couple of minor typo fixes (in a separate commit).
=> Set default ktlint version to 0.37.1

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ReportersTest.kt
=> Allow to override generated reports base directory.

plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/AbstractPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
Fixed #385 
Test and main code are in two separate commits to make it easier to demonstrate the problem. I would suggest squashing at merge.
=> Skip ktlint and report up-to-date if incremental task run contains only removed files

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/BuildCacheTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ReportersTest.kt
=> Fix tasks may not be cacheable due to overlapping outputs.

.github/workflows/build-and-check.yml, CHANGELOG.md, README.md, plugin/build.gradle.kts, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
- Enable running plugin tests on windows os via Github actions
- Fix Picoli [requires](https://picocli.info/#AtFiles) double `\\` in argument files
- Fix failing tests
Fixes #399 
Fixes #232
=> Fix running checks on windows does not fail on errors.

README.md
Made it more obvious that both plugins are needed to have the extra gradle tasks related to Idea and GIT
=> Requirement for GIT Pre-Commit Hooks Added

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/GitHookTasksTest.kt
When you commit part of a file the current git hook will change your commit to being the entire file.
This pr stashes the worktree before fmt, and unstashed before finished
=> git hook: don't commit whole file

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/GitHookTasksTest.kt
When a file is renamed git diff will return the status, old and new name. so `$2` will return the old name, `$NF` will return the last field in the string, the new name.
=> git hook: format renamed files

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/BaseKtLintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/KtLintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/KtLintFormatTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintWorkAction.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/EditorConfigTests.kt
Reset internal KtLint caches on any `.editorconfig` files change, so KtLint will repopulate caches and takes into account new content.
Additionally:
- slightly optimize `.editorconfig` files locate logic
- re-run KtLint on all sources on any `.editorconfig` files change, as change may affect rules behaviour
Fixes #456
=> Reset KtLint internal cache on .editorconfig files change

.github/workflows/changelog.yml
Verify that the pr is included in the CHANGELOG.md file, if the pr has the "skip news" label then it doesn't apply.
=> add changelog action

plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/TaskConfigurationAvoidanceTest.kt
Validates plugin does not create any tasks on configuration phase.
=> Add test to validate task configuration avoidance.

.github/workflows/build-and-check.yml, CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/Configurations.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/TaskCreation.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/GenerateBaselineTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/GenerateReportsTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/ConsoleReportWorkAction.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/GenerateBaselineWorkAction.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/GenerateReportsWorkAction.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintBaselineSupportTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/UnsupportedGradleTest.kt
This PR adds initial KtLint baseline support with following limitations:
- Format tasks ignore baseline, see [KtLint 1072 issue](https://github.com/pinterest/ktlint/issues/1072) for more details
- One baseline file is generated per one Gradle project (module). Merging baseline is not possible as KtLint actually uses `Reporter` interface to generate baseline file. Theoretically it will be possible to introduce special generate task in the root project that will trigger all subprojects, collects all errors and then write one baseline file, but let us see how big demand for it will be.
Fixes #414
=> Add KtLint baseline support

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/TaskCreation.kt
=> Fix gradle deprecation warning

.github/workflows/changelog.yml
It was using the wrong format: `(#123)` instead of `[#123](url)`
This will match:
```
[
#123
](
https://github.com/JLLeitschuh/ktlint-gradle/pull/123
)
```
=> Fix changelog workflow

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/GitHookTasksTest.kt
resolves #497
The logic was using `git stash push --keep-index` which keeps the index but also adds it to the stash. I've change the functionality to use a .diff file with the changes `git diff > unstaged.diff` and reapply it with `git apply --ignore-whitespace unstaged.diff`, in my opinion using `-3` would be better but then git applies it to the index, not the working copy.
There isn't a current version in the changes so I bumped it to 10.1.1
=> Resolve pre-commit hook causing conflicts

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintBasePlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/TaskCreation.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/BaseKtLintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/KtLintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/KtLintFormatTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintWorkAction.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
`BaseKtlintCheckTask` now extends `DefaultTask` plus implements `PatternFilterable` interface copying approach from `SourceTask`.
To better handle incremental formatting, plus handle the case of restored to pre-formatted state sources, Format task tracks pre-formatted files snapshot: file + content hash. In case sources has the files with same content hash as file in snapshot from previous task execution - format tasks fails up-to-date check and run format again on such files.
Fixes #423
Fixes #306
=> Rethink format task approach

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ConfigurationCacheTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/GitHookTasksTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/TestsCommon.kt
=> Fix install git hook task breaks configuration cache.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt
So if Kotlin Plugin configures immediately - registered plugin tasks could find expected existing one.
Fixes #495
=> Register Kotlin script tasks first.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/GitHookTasksTest.kt
The hook was using set -e, which meant that if the gradle command failed, then the saved unstaged changes in the diff file were never re-applied.
This change removes the use of set -e and Instead uses the exit code of the gradle task to indicate the success or failure of the hook after the unstaged changes are re-applied. This will ensure unstaged changes are always re-applied regardless of whether or not the check or format has failed or passed
=> Use Gradle command exit code as hook exit code

README.md
As suggested in #496, this PR adds the baseline generation task to README.
=> Add baseline generation task to Readme (#496)

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/Configurations.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
Keeping the default of being consumable exposes them to
variant-aware resolution when the project is depended
upon from another project.
Also configure the configurations as non-visible for
similar reasons: those are specific to this project's
build and there's no reason to consume them from
another project.
Fix #523
=> Configure configurations as resolvable non-consumable

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/TaskCreation.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/GenerateReportsTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/GenerateReportsWorkAction.kt
We use this gradle plugin in GitLab-CI and currently it always produces absolute paths which leads to broken links in the code quality report.
This PR adds the option `relative` analog to ktlint's CLI's `--relative` option, which does the same thing: Instead of outputting absolute paths in the report, the reports are made relative to the root project (ktlint make it relative to the workdir).
Currently this is only applied to the actual report file output, not the console output to still have clickable file paths in IntelliJ.
=> Add relative option similar to CLI's --relative

CHANGELOG.md, README.md, plugin/gradle/libs.versions.toml, plugin/settings.gradle.kts, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintBasePlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ConfigurationCacheTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtLintSupportedVersionsTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/testdsl/testAnnotations.kt, settings.gradle.kts
Based on [this](https://github.com/JLLeitschuh/ktlint-gradle/pull/595), I decided to create a PR that would bump ktlint to newer version. Instead of trying to update to the newest version in one PR, I find it more convenient to split the update into more smaller parts.
Ktlint 0.43.2 requires at least kotlin 1.4 API. That's why I needed to change the minimum required gradle version to 6.8.
In next PR I would try to update gradle from 7.1.1 -> 7.2 :)
=> bump kotlin to 1.5.31, bump ktlint to 0.43.2

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintInvocation.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintRuleLoader.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintWorkAction.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/AbstractPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ConfigurationCacheTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/DisabledRulesTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtLintSupportedVersionsTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintBaselineSupportTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/testdsl/testDsl.kt
support ktlint 0.46-0.48
add tests for 0.44 and 0.45 as well
This resolves https://github.com/JLLeitschuh/ktlint-gradle/issues/589
This resolves https://github.com/JLLeitschuh/ktlint-gradle/issues/607
=> support ktlint 0.45-0.48

CHANGELOG.md, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/GitHookTasksTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtLintSupportedVersionsTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/testdsl/testAnnotations.kt
add ktlint 0.48.2 to tested versions
update latest gradle to 7.6
=> update ktlint and gradle versions for testing

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintWorkAction.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtLintSupportedVersionsTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/testdsl/testDsl.kt
test additionalEditorconfigFile for all ktlint versions
=> warn when additionalEditorconfigFile is used in 0.47+ fixes #633

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/BaseKtLintCheckTask.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KotlinJsPluginTests.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintIdeaPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/testdsl/testAnnotations.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/testdsl/testDsl.kt
=> Work around reflective access errors on JVM 16+

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtilTest.kt
=> fix isRootEditorConfig

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/BaseKtLintCheckTask.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
add files previously found to have errors to the list of files to check in incremental builds. This will prevent the lint task from passing when errors are still present.
This should solve #491 and #576
=> add files previously found to have errors to incremental builds

CHANGELOG.md, plugin/gradle.properties
decrease plugin build workers to 4 to prevent thrashing
=> Reduce workers

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/BaseKtLintCheckTask.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
exclude deleted files from incremental checks (fixes #679)
=> exclude deleted files from incremental checks (fixes #679)

CHANGELOG.md, plugin/build.gradle.kts, plugin/src/adapter50/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintInvocation50.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtLintCompatibility.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintWorkAction.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtLintSupportedVersionsTest.kt
the ktlint changes were source-compatible but not bytecode compatible because of the use of optional parameters in the KtLintRuleEngine constructor
=> ktlint 0.50.0 support (fixes #686)

CHANGELOG.md, README.md, plugin/build.gradle.kts, plugin/settings.gradle.kts, plugin/src/adapter100/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintInvocation100.kt, plugin/src/adapter46/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintInvocation46.kt, plugin/src/adapter50/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintInvocation50.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/Configurations.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtLintCompatibility.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/TaskCreation.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/BaseKtLintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintWorkAction.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtLintSupportedVersionsTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/testdsl/TestDsl.kt
Ktlint 1.0 support (fixes #706)
Allow editorconfig overrides in ktlint 0.49+ (fixes #707)  using https://github.com/pinterest/ktlint/pull/2194
=> ktlint 1.0 support

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintWorkAction.kt
send an error log to the logger when catching an exception from ktlint before throwing the gradle exception
fixes #710
=>  improve error logging (fixes #710)

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintWorkAction.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtLintSupportedVersionsTest.kt
fix "additionalEditorconfig not supported until ktlint 0.49" warning when additionalEditorconfig is not being used
=> fix "additionalEditorconfig not supported until ktlint 0.49" warning

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/GenerateReportsTask.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ConfigurationCacheTest.kt
resolves #721 
The new test would fail before the changes to generate reports task and succeed afterwards
=> Fix configuration cache for relative paths

CHANGELOG.md, plugin/build.gradle.kts
This plugin is no longer needed as ktlint configuration is driven by .editorconfig now, which idea will respect out of the box
The plugin was already removed in 12.0.0, but we need to remove the declaration of the plugin in the build scripts to pass validation
=> remove KtLintIdea Plugin

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KotlinMultiplatformPluginTests.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
Use `DomainObjectCollection.all` instead of `Iterable<T>.forEach`. `all` executes the given function also against any objects subsequently added objects
The problem was introduced here
https://github.com/JLLeitschuh/ktlint-gradle/commit/a547de5601caec50ed827b1a5fe6c8207d41d218?diff=unified&w=0#diff-51eee411b698815c113da41ed3e9f5c31ebc7cb926df3580835df154cdd721e0L45
=> fix: apply configuration for source sets and targets that are added after the plugin is applied

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/BaseKtLintCheckTask.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/EditorConfigTests.kt
=> Fix additionalEditorconfig property not being accounted for up-to-date checks and caching

.gitignore, CHANGELOG.md, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/BuildCacheTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ConfigurationCacheTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ReportersTest.kt
fix tests which relied on a third party reporter in jcenter to use a third party reporter published to maven central (fixes #771)
=> fix tests which relied on a third party reporter in jcenter

CHANGELOG.md, README.md
This update supplements the documentation by adding instructions for configuring the Ktlint Gradle plugin using a version catalog. 
Since using version catalogs is now recommended officially and is used by default in newly generated projects, this addition provides essential guidance for both Groovy and Kotlin DSL users, making it easier to integrate the plugin into modern project setups.
=> Add Version Catalog Setup Instructions in README

README.md
In the README, **Tasks Added** list includes the task `ktlint[source set name]SourceSetCheck` twice.
The second listing of the task should actually be named `ktlint[source set name]SourceSetFormat`.
=> Update wrong task name in "Tasks Added" in README

CHANGELOG.md, README.md
As [mentioned in #726](https://github.com/JLLeitschuh/ktlint-gradle/pull/726#issuecomment-1984969722)
=> Removed IntelliJ plugin block from readme

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt
Force the pre-commit script to continue even if there is error to ensure the unstaged files are reapplied.
It seems that in some case/environment the commit hook is launched with set -e. In this case, the unstaged files are not reapplied and can be lost.
=> pre-commit hook : fix losing unstaged files on error

.github/workflows/build-and-check.yml, CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt
When running one of the Git hook tasks together with another task, Gradle will complain with an error:
> Reason: Task ':addKtlintCheckGitPreCommitHook' uses this output of task ':samples:kotlin-reporter-using:compileKotlin' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
This is caused by `@InputDirectory` marking the entire project root and contents as input, so any task that modifies any file in the project will cause Gradle to add an implicit dependency.
You can see this behaviour by running `./gradlew compileKotlin addKtlintCheckGitPreCommitHook`.
Build result on the first commit of this PR, to show it failing: https://github.com/ntkoopman/ktlint-gradle/actions/runs/13514290368/job/ …
=> Fix dependency issue for git hook tasks

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintBasePlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/android/KtlintPluginAndroidTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/testdsl/TestAnnotations.kt
Gradle 9 Support
remove use of ConfigureUtil
update max kotlin version for testing to 2.2.0
=> Gradle 9 Support
