CHANGELOG.md, src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt
Fixes #14 .
Checked that this change is working for plain kotlin project and android kotlin project.
=> Add that java check task is also depends on ktlintCheck task.

CHANGELOG.md, README.md, plugin/build.gradle.kts, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/Reporter.kt
=> Add configuration parameter `android` with default value to false

CHANGELOG.md, plugin/build.gradle.kts, samples/build.gradle.kts
=> Update kotlin to 1.1.60 version.

README.md
Added documentation how-to apply plugin for project modules using new Gradle plugins api.
Output of #44 issue.
=> Update README with how-to apply for modules.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, samples/kotlin-js/build.gradle.kts, samples/kotlin-js/src/main/kotlin/org/jlleitschuh/gradle/ktlint/sample/js/main.kt, settings.gradle.kts
Part of #58:
- Enable support for "kotlin2js" (javascript) plugin
- Add Kotlin javascript sample
=> Enable Kotlin javascript plugin support

CHANGELOG.md, build.gradle.kts, plugin/build.gradle.kts, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, samples/kotlin-native/build.gradle.kts, samples/kotlin-native/src/main/kotlin/org/jlleitschuh/gradle/ktlint/sample/native/main.kt, settings.gradle.kts
#58: Add support for kotlin native (konan) plugin.
=> Add kotlin native support

CHANGELOG.md, README.md, plugin/build.gradle.kts, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt
PR to make a new release `3.1.0` of plugin.
=> New release 3.1.0

CHANGELOG.md, plugin/build.gradle.kts
=> Prepare for next development iteration.

plugin/build.gradle.kts
just for the sake of using the latest
=> Upgrade com.gradle.plugin-publish to 0.9.10

plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/reporter/Reporter.kt
in order to support paths with spaces
=> Quote reporter output path

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, samples/android-app/build.gradle.kts
=> Remove usage of deprecated Gradle features.

CHANGELOG.md, README.md, plugin/build.gradle.kts
=> Release version 3.2.0.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt
this plugin is a version behind and quite alot changed in ktlint 0.20.0
Is this pull request enough to just create a new small patch?
Thanks for your work on this plugin!
=> Please update to ktlint 0.20.0

plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/reporter/Reporter.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/AbstractPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginVersionTest.kt
=> Check for spaces in output path for Ktlint versions earlier than 0.20.0

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintApplyToIdeaTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
This task applies style settings globally - in user home IDEA settings
folder. 
Per project setting generation is only available from KtLint version `0.22.0`.
Closes #91.
=> Add applyToIdeaGlobally task.

CHANGELOG.md, README.md, plugin/build.gradle.kts
=> New release 5.1.0.

README.md, samples/kotlin-rulesets-using/build.gradle.kts
Restructure project readme:
- Added "Table of contents"
- Added "Supported Kotlin plugins" section
- Added "FAQ" section and few questions/answers there
Closes #19.
Closes #109.
=> Restructure project readme

CHANGELOG.md, plugin/build.gradle.kts, plugin/buildSrc/src/main/kotlin/PluginDependencies.kt
=> Prepare for new development cycle.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, samples/kotlin-ks/build.gradle.kts
=> Add support for console colored output.

README.md
There's a badge now 😄 
https://github.com/shyiko/ktlint#badge
=> Add code style badge to README.md

CHANGELOG.md, README.md, plugin/build.gradle.kts
Forget to change release type from SNAPSHOT in previous release :disappointed:
=> New release 6.1.1.

CHANGELOG.md, plugin/build.gradle.kts, plugin/buildSrc/src/main/kotlin/PluginDependencies.kt
=> New dev cycle

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, samples/kotlin-mpp-android/build.gradle.kts, samples/kotlin-mpp-android/src/commonMain/kotlin/org/jlleitschuh/gradle/ktlint/sample/mppandroid/LocationProvider.kt, samples/kotlin-mpp-android/src/main/AndroidManifest.xml, samples/kotlin-mpp-android/src/main/java/org/jlleitschuh/gradle/ktlint/sample/mppandroid/AndroidLocationProvider.kt, samples/kotlin-mpp/build.gradle.kts, samples/kotlin-mpp/src/commonMain/kotlin/org/jlleitschuh/gradle/ktlint/sample/mpp/CommonInterface.kt, samples/kotlin-mpp/src/jsMain/kotlin/org/jlleitschuh/gradle/ktlint/sample/mpp/JsCommon.kt, samples/kotlin-mpp/src/jvmMain/kotlin/org/jlleitschuh/gradle/ktlint/sample/mpp/JvmCommon.kt, samples/kotlin-mpp/src/jvmMain/kotlin/org/jlleitschuh/gradle/ktlint/sample/mpp/main.kt, samples/kotlin-mpp/src/linuxMain/kotlin/org/jlleitschuh/gradle/ktlint/sample/mpp/LinuxCommon.kt, settings.gradle.kts
=> Add support for new kotlin multiplatform plugin

plugin/build.gradle.kts
Trying to fix following failed CI pipeline: https://travis-ci.org/JLLeitschuh/ktlint-gradle/builds/451544513
TL;DR base plugin is missing publishing id and display name.
=> Added missing base plugin publishing info.

README.md
=> Added a faq entry how to use ReporterType in external Gradle scripts.

CHANGELOG.md, README.md, plugin/build.gradle.kts
=> New 6.3.1 release.

README.md
Related Gradle issue: https://github.com/gradle/gradle/issues/1477
=> Add Gradle plugin portal badge to readme.

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintApplyToIdeaTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginVersionTest.kt
This should simplify code and tests.
=> Set minimal supported ktlint version to 0.22.0.

CHANGELOG.md, README.md, plugin/build.gradle.kts
=> New 7.0.0 release.

plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt
ktlint 0.30.0 was just released https://github.com/shyiko/ktlint/releases/tag/0.30.0
=> Update default KtLint version to 0.30.0

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
=> Fix plugin is always using default ktlint version.

plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt
=> Fix ClassNotFoundException due to Gradle ClassInspector issue

buildSrc/src/main/kotlin/SamplesDependencies.kt, plugin/build.gradle.kts, plugin/buildSrc/src/main/kotlin/PluginDependencies.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/AbstractPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintIdeaPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginVersionTest.kt
=> Update tests to Junit5

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintBasePlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/AbstractPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt, samples/kotlin-rulesets-using/build.gradle.kts
Fixes #98 
@JLLeitschuh can you check if I am doing right with extension and additional paths for kotlin script files?
=> Add task for kotlin script files

CHANGELOG.md, README.md, plugin/build.gradle.kts, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, samples/android-app/build.gradle.kts
Fixes #217 
Includes setup for `7.2.1` release.
=> Fix task failed to apply

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/AbstractPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
=> Add flag to enable ktlint experimental rules.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
Closes #219.
Unfortunately, I can't anymore reproduce the warning from Android plugin in our samples (seen it before).
=> Proper way to lazy add ktlint dependency.

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintBasePlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/PluginUtil.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/AbstractPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/EditorConfigTests.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/TestsCommon.kt
=> Add support for additional editorconfig file

CHANGELOG.md, README.md, build.gradle.kts, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KotlinJsPluginTests.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/TestsCommon.kt, samples/kotlin-kotlin2js/build.gradle.kts, samples/kotlin-kotlin2js/src/main/kotlin/org/jlleitschuh/gradle/ktlint/sample/js/main.kt, settings.gradle.kts
=> Add support for new "org.jetbrains.kotlin.js" plugin.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt
=> Add support for "com.android.dynamic-feature" plugin.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/Configurations.kt
=> Fix configuration could be configured after been resolved.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintApplyToIdeaTask.kt
Use new subcommand introduces in [ktlint 0.35.0](https://github.com/pinterest/ktlint/blob/master/CHANGELOG.md#0350---2019-10-12) to apply code style settings to IDEA and reshuffle arguments so they will work in both cases.
Close #311
=> Use proper order of arguments for apply style to IDEA command.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/reporter/ReporterType.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ReportersTest.kt, samples/kotlin-ks/build.gradle.kts
=> Add html reporter

plugin/settings.gradle.kts, settings.gradle.kts
It's free and it's a good way to view test results from contributor PRs.
=> Enable build scan support for our build

.travis.yml, plugin/build.gradle.kts, plugin/buildSrc/src/main/kotlin/PluginDependencies.kt
This plugin will automatically sync changelog to github releases page on a new plugin release.
=> Integrate "com.github.breadmoirai.github-release" plugin.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt
=> Fix git hook will fail to run on multiple kotlin files.

README.md
=> Add faq entry how-to filter files located outside project dir.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintFormatTask.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/reporter/KtlintReport.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ConfigurationCacheTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/TestsCommon.kt
=> Support for configuration cache

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
=> Fix KtLint was not checking files with whitespaces either in path or name.

README.md
=> Add faq entry about Kotlin version pinning.

plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt
Update ktlint to 0.39.0.
More info about 0.39.0:
https://github.com/pinterest/ktlint/releases/tag/0.39.0
=> Update ktlint to 0.39.0

.github/workflows/build-and-check.yml, .gitignore, plugin/build.gradle.kts, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/AbstractPluginTest.kt
Should speedup plugin test suite execution time.
=> Enable running tests in parallel.

README.md
=> Add required repositories info into project README.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/GenerateReportsTask.kt
=> Fix plugin fails to apply on non-Kotlin project.

build.gradle.kts, plugin/build.gradle.kts, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/EditorConfigTests.kt, samples/kotlin-gradle/build.gradle, samples/kotlin-reporter-using/build.gradle.kts
=> Remove all usages of 'jcenter()' repository.

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintWorkAction.kt
=> Print path to file which KtLint failed to parse.

README.md
=> Updating references to MPP samples

README.md
Hi! I encountered a problem when trying to change the memory configuration for KtLint in our project. The example did not work for me.
I changed the README to how it worked (Kotlin Script).
Let me know, what you think. 😊 🙏
=> README: Fix example on how to increase memory limit

CHANGELOG.md, README.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/reporter/ReporterType.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/ReportersTest.kt
Added support for the ktlint sarif reporter: https://github.com/pinterest/ktlint/pull/1113
It only available in the 0.42.0-SNAPSHOT ktlin version at moment.
=> Added support for sarif reporter

README.md
Also fix misc issues with the readme
=> Update read me to favor plugins block

CHANGELOG.md, plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/GitHookTasksTest.kt, plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/TestsCommon.kt
Fixes https://github.com/JLLeitschuh/ktlint-gradle/issues/557
=> Check if hooks folder exists before using it

.github/workflows/build-and-check.yml, CHANGELOG.md
=> test against all supported versions of the JVM

.github/workflows/build-and-check.yml
=> Update to `actions/upload-artifact@v4`

.github/workflows/build-and-check.yml
Signed-off-by: Jonathan Leitschuh <Jonathan.Leitschuh@gmail.com>
=> Remove deprecated `::set-output` in Action

.github/workflows/trigger-release.yaml
Signed-off-by: Jonathan Leitschuh <Jonathan.Leitschuh@gmail.com>
=> Fix docs in Trigger Release workflow

.github/workflows/codeql.yml
Closes: https://github.com/JLLeitschuh/ktlint-gradle/issues/797
Signed-off-by: Jonathan Leitschuh <Jonathan.Leitschuh@gmail.com>
=> Add advanced CodeQL Job

README.md
This was removed in https://github.com/JLLeitschuh/ktlint-gradle/pull/726 but is still referenced in the readme
Seems this was missed in https://github.com/JLLeitschuh/ktlint-gradle/pull/775
See also https://github.com/JLLeitschuh/ktlint-gradle/issues/149#issuecomment-1964398988
=> Update README to remove idea mentions

.github/workflows/codeql.yml
Explicitly invoke the `classes` in the CodeQL action
=> Attempt to Fix CodeQL by invoking `classes` task
